### ISSUE TITLE
Pagination Related

### ISSUE THREAD

**Issue by Bhumesh-45678** [alexmamo/FirestorePaginationJetpackCompose#1]
Hi alex . I want to add pagination in my project.
I use firestore as database and language is java in android studio. Please help me to how pagination is implement. On internet no one example for java, all examples uses kotlin. Please explain pagination in java.
@alexmamo

**Comment by AlexMamo** [comment]
Kotlin is for a few years now, the preferred language for Android development. So you either start to learn Kotlin, or you try to convert the actual code to Java. That's however not an issue to the actual repo.
